# Generated by Django 5.1.7 on 2025-04-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encrypted_key',
            field=models.TextField(default='key'),
        ),
    ]
