# Generated by Django 5.1.7 on 2025-04-09 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_encrypted_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='encrypted_key',
        ),
    ]
